### ISSUE TITLE
Add endpoint to trigger re-import when required

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#105]
Add endpoint to trigger re-import when required

**Comment by sajo-ebi** [comment]
@ala-ebi we need a UI button on the Submssion Details page 'Complete Submission' which the curators clicks once they have finished their changes in Depo Curation

**Comment by sajo-ebi** [comment]
Backend is ready to be consumed by UI

**Comment by sajo-ebi** [comment]
@ala-ebi the API to be called is [	http://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1submissions/{submissionId} ](http://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/{submissionId} )

Http Method -: Patch
Payload -:

{
    "submission_status": "SUBMITTED"
}
