### ISSUE TITLE
Create new Bakend Service and Endpoint to update Free text sample description

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#110]
Create new Bakend Service and Endpoint to update Free text sample description

**Comment by sajo-ebi** [comment]
API has been created for getting Sample Description for submission & updating multiple studies with submssionId

[Get Sample Description for Submission](https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/submissions/62279db351101e0001a16435/studies/sampledescription)

[Patch Sample Description for Submission](https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/submissions/62279db351101e0001a16435/studies/sampledescription)
