### ISSUE TITLE
Duplicate EFO Traits Issue

### ISSUE THREAD

**Issue by sajo-ebi** [EBISPOT/gwas-curation-service#138]
Issue has been identified where the EFO Trait names are duplicated with different URI but this is not valid & Trait names shouldn't be duplicated . We need to replicate the Curation Code EFO Trait Behaviour

**Comment by sprintell** [comment]
@sprintell  
We previously check for unique URI in depocuration 

Trait Names and the URI must be unique, also the URI validation must be done in the new system

**Comment by sajo-ebi** [comment]
HI @earlEBI this is available in Depo Curation Sandbox environment kindly validate if it is fine for you

**Comment by earlEBI** [comment]
@sajo-ebi seems good, thanks
