### ISSUE TITLE
API endpoint to get All studies resources from the database

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#139]
**Description:**
As developer
I want an api endpoint
So that when I send a GET request, hateoas, paginated list of all studies in the database is returned in JSON Format

**Management Rules:**
Rule 1: Endpoint - /v1/studies
Rule 2: HTTP Request Method - GET
Rule 3: Endpoint should accept filter, and sort parameters as in /v1/studies?efo-trait=...&page=0&size=20&sort=...
Rule 4: Search filter should be available for: efo-trait, reported-trait, study-flag, and notes
Rule 5: Returned Study Json entity must include: GCST, PMID, Journal publication date, Author name, Title, EFOTrait, ReportedTrait, Notes
Rule 6: HATEOAS, sorting, pagination, and some search and filter using QueryDsl

**Acceptance Tests:**
When the front end sends a GET request to the endpoint
Hateoas compliant list of studies is returned in JSON Format

Given sorting, pagination, and/or some search and filter parameters
When the front end sends a GET request to thesame endpoint
Hateoas compliant filtered list of studies satisfing the conditions in the url parameter must be returned

**Comment by sajo-ebi** [comment]
Based on discussion with Yomi, it was agreed that Solr needs to be used to Search Study related data, there need to be a separate component to index the Solr fields & possible use Rabbit MQ to listen toe events on the study table related updates

**Comment by sajo-ebi** [comment]
@sprintell we have also Studies with out Pmid , should the API also include Body of work related Entities
