### ISSUE TITLE
API endpoint to get all curators

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#145]
**Description:**
As developer
I want an api endpoint
So that when I send a GET request, list of all curators in the database, is returned

**Management Rules:**
Rule 1: Endpoint - /v1/curators
Rule 2: HTTP Request Method - GET
Rule 3: The list of curators must be all curators registered with accounts in the depocuration app by surname, e.g. Harris, Sollis including (Unassigned, Level 1 curator, Level 2 curator, GWAS Catalog)

**Acceptance Tests:**
Given no parameter
When the front end sends a GET request to the endpoint
List of publication status is returned in JSON Format

**Comment by sajo-ebi** [comment]
@sprintell , The surname could match for multiple curators , should we instead should full name or username field optional for curators to create unique?

**Comment by ljwh2** [comment]
Pending development of UI

**Comment by sprintell** [comment]
This is done, but there is something wrong with the endpoint struggling to Marshall PagedResource

https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/curators

This should be a quick fix @sajo-ebi 


Could not marshal [PagedResource { content: [Resource { content: uk.ac.ebi.spot.gwas.deposition.dto.curation.CuratorDTO@56b21dfa, links: [<http://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/curators/634592c88348bd70828d79f1>;rel="parent"] }, Resource { content: uk.ac.ebi.spot.gwas.deposition.dto.curation.CuratorDTO@85d69d69, links: [<http://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/curators/634594698348bd70828d79f3>;rel="parent"] }, Resource { content: uk.ac.ebi.spot.gwas.deposit ...

**Comment by sajo-ebi** [comment]
@sprintell the API is working , probably  you are getting error because you tried Url without authentication token , it should work in postmane with authentication token
