### ISSUE TITLE
API endpoint to get all publication status

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#146]
**Description:**
As developer
I want an api endpoint
So that when I send a GET request, paginated list of all valid publication status in the database, is returned

**Management Rules:**
Rule 1: Endpoint - /v1/publication-status
Rule 2: HTTP Request Method - GET
Rule 3: A mechanism should exist to prepopulate the database with the 14 status below
 1. Awaiting submission
 2. Submission complete
 3. Level 2 curation done
 4. Awaiting EFO
 5. Awaiting literature
 6. Awaiting mapping
 7. Curation abandoned
 8. Pending author query
 9. Pending curation query
 10. Preliminary review done
 11. Scientific pilot
 12. Publish Study
 13. Unpublished from Catalog
 14. Permanently unpublished from Catalog

**Acceptance Tests:**
Given no parameter
When the front end sends a GET request to the endpoint
List of publication status is returned in JSON Format

**Comment by sajo-ebi** [comment]
Hi @ljwh2 I checked the Prod DB for Curation status , There are 22 different statuses in CUration DB currently , I know curators have asked to remove some but still wanted to check that no status which is supposed to be there is not captured in this story. Below mentioned is the list of status -:

- Level 1 ancestry done
- Level 2 ancestry done
- Level 1 curation done
- Level 2 curation done
- Publish study
- Awaiting Curation
- Outstanding Query
- CNV Paper
- Curation Abandoned
- Conversion Problem
- Unpublished from catalog
- Pending author query
- Awaiting EFO assignment
- Requires re-curation
- Preliminary review done
- Level 3 curation done
- Awaiting mapping
- Awaiting literature
- Permanently unpublished from catalog
- Scientific pilot
- Requires Review

**Comment by sprintell** [comment]
This looks like a a little fix, the endpoint https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/publication-status is not existing.

I only saw https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/curator-status

It should be publication status not curation status

**Comment by sajo-ebi** [comment]
have changed the Endpoint as per the ticket , will deploy to Sandbox

**Comment by sprintell** [comment]
@ala-ebi corresponding changes in UI

**Comment by sajo-ebi** [comment]
@sprintell the API has been deployed with uri change as expected
