### ISSUE TITLE
API endpoint to create one or more publication resources

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#172]
**Description:**
As developer
I want an api endpoint
So that when I send a post request with a list of PMIDs as payload new publications are created in the database

**Management Rules:**
**Rule 1:** Endpoint - /v1/publications
**Rule 2:** HTTP Request Method - POST
**Rule 3:** Proper Assemblers, disassemblers and DTO with validation rules
**Rule 4:** The Endpoint should accept validated list of pubmedIDs
**Rule 5:** Standard custom exception be thrown if operation fails
**Rule 6:** The service must automatically extract publication metadata from Europe PMC into the database: Author, Title, Journal, Publication date.
**Rule 7:** The service must assign new publication default values of Curator = "Level 1 curator", and Status = "Awaiting submission".
**Rule 8:** Payload containing list of created publications and/or not created must be returned

**Reusable Components:**
Most of the required components and EuropePMC endpoints can be re-used from here http://bit.ly/3VnkNhb  

**Acceptance Tests:**
Given a JSON payload containing list of PMIDs
When the front end sends a post request with the payload to the endpoint

1. If no validation error occurs, the publications should be saved, payload with publicationId, PMID, Author, Title, Journal and statusReport, createdBy, and createDate should be returned

2. If any of the PMID existed previously in the database, payload with - publicationId, PMID, Author, Title, Journal and statusReport must be returned with statusReport = “PMID already exists”.

3. If PMIDs are not found in EuropePMC, payload with - PMID, and statusReport must be returned with statusReport = “PMID not found”.

4. If EuropePMC API fails, payload with - PMID, and statusReport must be returned with statusReport=“The EuropePMC API could not be contacted, seek help”

**Comment by ljwh2** [comment]
Back end is ready for this - needs review and UI part

**Comment by sprintell** [comment]
Hi @sajo-ebi  could you please report on this ticket, specifying where the test endpoint  is .../v1/publications in the sandbox ...

**Comment by sprintell** [comment]
Here is the endpoin: https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/publications 

This ticket can be closed

**Comment by ljwh2** [comment]
Need to keep open for testing  till UI is ready

**Comment by sprintell** [comment]
@sprintell test this via postman

**Comment by ljwh2** [comment]
PMIDs for testing: 37076585 36350656 34870259 32876357

**Comment by sprintell** [comment]
Add initital curation status on creation @sajo-ebi @ljwh2 wil also provide gidance on the possibility of having an inital curator "UNASSIGNED"

**Comment by ljwh2** [comment]
Publications should be added with initial curator "level 1 curator"

**Comment by ljwh2** [comment]
@ala-ebi to complete this
