### ISSUE TITLE
Publication Notes - API endpoint to get All Notes for a given publication

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#189]
**Description:**
As developer
I want an api endpoint
So that when I send a GET request, paginated list of all notes in the database for a given publication is returned

**Management Rules:**
Rule 1: Endpoint - /v1/publications/{publicationId}/notes
Rule 2: HTTP Request Method - GET
Rule 3: Endpoint should accept filter, and sort parameters as in /v1/reported-traits?trait=...&page=0&size=20&create_date=
Rule 4: HATEOAS, sorting, pagination should be returned

**Acceptance Tests:**
Given no parameter
When the front end sends a get request to the endpoint
Hateoas compliant list of publication notes is returned in JSON Format

**Comment by sajo-ebi** [comment]
Api can be tested in Sandbox [https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/publications/{pubId}/notes](https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/publications/{pubId}/notes)
