### ISSUE TITLE
Publication Notes - API endpoint to Update a single Publication Note Resource:

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#190]
**Description:**
As developer
I want an api endpoint
So that I can change / update an existing publication note

**Management Rules:**
Rule 1: Endpoint - /v1/publications/{publicationId}/notes/{noteId}
Rule 2: HTTP Request Method - PUT
Rule 3: Endpoint should accept noteId
Rule 4: The Endpoint should accept validated NoteDTO Object
Rule 5: Endpoint should return full attributes of the updated publication note

**Acceptance Tests:**
Given a wrong note id
When user sends a put request to the endpoint
Properly described Entity not found exception should be returned in JSON format

**Given invalid payload**
When user sends a put request to the endpoint
Properly described Exception should be returned in JSON format, detailing out what is wrong

**Given a correct note Id and valid payload**
When the front end sends a put request to the endpoint
The single note must be updated

**Comment by sajo-ebi** [comment]
@sprintell I think we don't need this API as discussed the Publication Notes should be one to one mapping with Pmid & the notes should be an array , so we will always have the Notes as an Update operation for Pmid , so we need just one API for Updating or Adding notes

**Comment by sajo-ebi** [comment]
deployed to Prod , API can be tested in Sandbox [https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/publications/{pubId}/notes/{noteId}](https://wwwdev.ebi.ac.uk/gwas/depo-curation/api/v1/publications/{pubId}/notes/{noteId})
