### ISSUE TITLE
Copy all old Publications and all child Objects from Oracle Database to MONGO 

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#197]
The readability of this should be tested and verified in sandbox first

**Comment by sajo-ebi** [comment]
The data has been updated for Publication table in Sandbox environment & can be tested

**Comment by ljwh2** [comment]
@ljwh2 to test

**Comment by sprintell** [comment]
@ljwh2 to test this, and also as discussed with @sajo-ebi the case of syncronizing publications now created i MongoDb back to Oracle database. The sync or import doesn't capture this atm

**Comment by sprintell** [comment]
@earlEBI should test this

**Comment by earlEBI** [comment]
All publications in the queue / Catalog are in Depocuration sandbox.
