### ISSUE TITLE
Change "User Requested" and "Open Targets" flags to be part of the publication instead of submission

### ISSUE THREAD

**Issue by ala-ebi** [EBISPOT/gwas-curation-service#199]
Delete both flags from the submission and add them to the publication

To be deleted from the following projects:

- [x] commons
- [x] deposition
- [x] curation
- [ ] ingest
- [ ] goci

**Comment by ala-ebi** [comment]
removing from submission is deprioritised, will come after UI

**Comment by ljwh2** [comment]
@earlEBI to confirm this is working in prod, if so ticket can be closed

**Comment by earlEBI** [comment]
I confirm:
- there is no tracking event created for ticking Open Targets - agreed with Laura ok
- OT is saved in Depocuration overnight. ok
- OT tick is not imported to Curation App - agreed with Laura ok

**Comment by ljwh2** [comment]
@earlEBI has some concerns that the flags aren't being saved, re-opening the ticket to monitor this.

**Comment by earlEBI** [comment]
Here is an example of a PMID which has open targets: 'true' in MongoDB submissions table but the check box is not ticked in DepoCuration or in the CurationQueueStats.txt file:

PMID 38565336

Here is a .csv file of all submissions with OpenTargets = true, where all but one is not OT=true at the publication level:
[gwasdepo.publications-OT-true.csv](https://github.com/user-attachments/files/17277728/gwasdepo.publications-OT-true.csv)

I will continue to monitor going forward if publications remain OT=true after publishing.

**Comment by ala-ebi** [comment]
PMID 38063329 to fix also

**Comment by ala-ebi** [comment]
The boxes in the Submission page are disabled, so you can only see and but not edit them.
There was a bug in that page whereby the checkbox will be ticked when the db value is false but unticked when it's not present, the former happens after you tick and then until the checkbox. The bug is purely in the submission page UI and does not affect the data.

this is now fixed, thanks for reporting.

**Comment by ala-ebi** [comment]
also filled the OTAR flag in the publications of the csv file in a comment above

**Comment by earlEBI** [comment]
38789058 is currently Open Targets = True in DepoCuration App and CurationQueue.txt
Monitoring.
