### ISSUE TITLE
Feature to expose or publish changes in Metadata in Depo-Curation database to  

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#200]
At the moment, the Yaml **CREATE** process retrieves the data from the ingest API while old studies are retrieved via the Rest API.

This feature wil allow **UPDATE** of the yaml file 

This data could either be published to the GWAS RabbitMq for Celery to retrieve while @karatugo impleements [this ticket ](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1225) to consume it and update the corresponding yaml file

Alternatively, this data could be exposed via the ingest API siilar to the yaml creation process

**Comment by ljwh2** [comment]
working in sandbox
