### ISSUE TITLE
Migrate publication literature files from Old curation App to Mongo Database

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#220]
✅  Investigate possibility of exporting the old curation literature files 
✅  Compress and move the 28GB old old curation literature files 
✅  Analyse the directory structure since its arranged by studies and its now required to be stored by publications
✅  Export all exisiting publicatons and studies in Oracle database as at date
✅  Create a throw away script to:
-- ✅ Query all the existing publications and Studies in Oracle database
-- ✅ Traverse the old file directory for all study folders belonging to each publication
-- ✅ Retrieve the literature files for each study belonging to a publication
-- ✅ Save only the name of the literature files in new Mongo Literature database
-- ✅ Dynamically create a folder for that particular publication in the FTP
-- ✅ Migrate all the corresponding study files to the publication folder and push them to the publication folder in FTP

**Comment by sprintell** [comment]
- 28,800 old curation files are now accessible in the FTP directory: /nfs/ftp/private/gwas_cat/curation_app_literature_upload

- Every publication has a folder, with all literature files stored in it 

- Metadata of all the 28,800 literature files are available in MongoDB under the Document Schema literature-files

- Hence the depo-curation app, can present them as well, and access them for retrieval

**Comment by eks-ebi** [comment]
I counted the total number of PMID folders, and checked a few folders and all uploaded files look correct
