### ISSUE TITLE
Create API endpoint to get All reported trait resources

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#45]
Description:
As developer
I want an api endpoint
So that when I can get paginated list of all reported traits in the database in JSON Format

Management Rules:
Rule 0: Endpoint must be accessible to curator role only
Rule 1: Endpoint - /v1/reported-traits
Rule 2: HTTP Request Method - GET
Rule 3: Endpoint should accept filter, and sort parameters as in /v1/reported-traits?trait=...&page=0&size=20 &sort=name,desc
Rule 4: HATEOAS, sorting, pagination, and some search and filter specification

Acceptance Tests:
Given no parameter  
When the front end sends a get request to the endpoint
Hateoas compliant list of reported traits is  returned in JSON Format
Given sorting, pagination, and/or some search and filter parameters
When the front end sends a get request to the endpoint
Hateoas compliant filtered list of reported traits satisfying the conditions in the url parameter must be returned

**Comment by sajo-ebi** [comment]
API has been implemented in Sandbox . The details are

Http Method : GET

API : [http://193.62.54.159/curation-traits/v1/reported-traits](http://193.62.54.159/curation-traits/v1/reported-traits)
