### ISSUE TITLE
Create API endpoint to get one reported trait resource

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#46]
Description:
As developer
I want an api endpoint
So that I can get full details of a single reported trait in JSON Format

Management Rules:
Rule 0: Endpoint must be accessible to curator role only
Rule 1: Endpoint - /v1/reported-traits/{reportedTraitId}
Rule 2: HTTP Request Method - GET
Rule 3: Endpoint should accept reported trait id
Rule 4: Endpoint should return full attributes of the reported traits including creator, modifier and time info

Acceptance Tests:
Given a correct reported Id
When the front end sends a get request to the endpoint
A single corresponding reported traits is returned in JSON Format
Given a wrong reported id
When the front end sends a get request to the endpoint
Properly described Resource not found exception should be returned as JSOn payload

**Comment by sajo-ebi** [comment]
API has been developed & deployed in Sandbox . The details are as below -:

API

Http Method : GET

http://193.62.54.159/curation-traits/v1/reported-traits/{traitId}

Response :

`{
    "diseaseTraitId": "60fb0d9a3c35c70001efb661",
    "trait": "wg rh intensity-contrast paracentral",
    "created": {
        "user": {
            "name": "Sajo John",
            "email": "sajo@ebi.ac.uk",
            "nickname": "aef584dc726a5586b40955f1551b963e2e839b32",
            "userReference": "usr-8f78675b-80bc-4527-8948-9456c9f0c4dd",
            "domains": [
                "self.GWAS_Curator"
            ]
        },
        "timestamp": "2021-07-23T18:42:34.290Z"
    },
    "_links": {
        "self": {
            "href": "http://193.62.54.159/curation-traits/v1/reported-traits/60fb0d9a3c35c70001efb661"
        }
    }
}`
