### ISSUE TITLE
Create API endpoint to fully Update single reported trait resource

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#47]
Description:
As developer
I want an api endpoint
So that I can change / update all the attributes of a single reported trait

Management Rules:
Rule 0: Endpoint must be accessible to curator role only
Rule 1: Endpoint - /v1/reported-traits/{reportedTraitId}
Rule 2: HTTP Request Method - PUT
Rule 3: Endpoint should accept reported trait id
Rule 4: The Endpoint should accept validated ReportedTrait DTO Object
Rule 5: Endpoint should return full attributes of the updated reported trait

Acceptance Tests:
Given a wrong reported id
When user sends a put request to the endpoint
Properly described Entity not found exception should be returned in JSON format

Given invalid payload
When user sends a put request to the endpoint
Properly described Exception should be returned in JSON format, detailing out what payload attribute is wrong

Given a correct reported Id and valid payload
When the front end sends a put request to the endpoint
The single reported trait must be updated
Hateoas compliant list of reported traits is  returned in JSON Format

**Comment by sajo-ebi** [comment]
The API has been implemented in Sandbox , the details are 

```
Http Method: PUT

API :[http://193.62.54.159/curation-traits/v1/reported-traits/61017bc9d30ea7000196bcb0]( http://193.62.54.159/curation-traits/v1/reported-traits/61017bc9d30ea7000196bcb0)

Payload :  {
 "trait": "wg rh intensity-contrast superiorparietal23"
}
```
