### ISSUE TITLE
Create API endpoint to delete one or more reported trait resource

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#48]
Description:
As developer
I want an api endpoint
So that I can delete one or more reported trait

Management Rules:
Rule 0: Endpoint must be accessible to curator role only
Rule 1: Endpoint - /v1/reported-traits/{reportedTraitIds}
Rule 2: HTTP Request Method - DELETE
Rule 3: Endpoint should accept List of reported trait ids
Rule 4: Endpoint should return full attributes of the updated reported trait

Acceptance Tests:
Given a wrong reported id
When user sends a delete request to the endpoint
Properly described Entity not found exception should be returned in JSON format

Given a correct reported id that is already assigned to a study
When user sends a delete request to the endpoint
Properly described Entity specifying that the resource cannot be deleted should be returned.

Given a correct reported Id or List of reported Ids
When the front end sends a delete request to the endpoint
The corresponding reported trait must be deleted
Http 204 must be returned

**Comment by sajo-ebi** [comment]
API has been deployed in Sandbox . The details are -:

`API -> http://193.62.54.159/curation-traits/v1/reported-traits/61017bb0d30ea7000196bcaf,61017b84d30ea7000196bcae

Http Method: Delete`
