### ISSUE TITLE
API endpoint to run similarity analysis of reported traits

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#52]
Description:
As developer
I want an api endpoint
So that I can upload csv file of traits to check for existence of similar traits in the database ranked according to degree of similarity

Management Rules:
Rule 1: Endpoint - /v1/reported-traits/analysis
Rule 2: HTTP Request Method - POST
Rule 3: Endpoint should accept a single column validated Multipart file containing rows of reported traits, numerical value indicating analysis threshold
Rule 4: Standard customized exception be thrown if operation fails
Rule 5: A unique id will be generated for the analysis
Rule 5: Endpoint should return list of created repoted traits with their autogenerated ids

Acceptance Tests:
Given invalid csv file  
When user sends a post request with the multipart file to the endpoint
Properly described Exception should be returned in JSON format, detailing what is wrong

Given valid csv file uploaded and analysis threshold value
A unique id will be generated for the analysis
Cosine distance and levenshtein distance will be computed for each term for each uploaded trait based on all the traits in the database
3 column result is generated for each trait (degree of similarity, user submitted trait, similar term found)
The analysis result in cached in memory, retrievable in future by the analysisId
This analysis should run asynchronously while the analysisId is returned to the user, which is further used to download the analysis file

**Comment by sajo-ebi** [comment]
API has been deployed in Sandbox , the details are :

```
API : http://193.62.54.159/curation-traits/v1/reported-traits/fileupload/analysis
Method : POST
Payload : [https://app.zenhub.com/files/309315145/906718b8-0b2a-4ce1-ab39-b3265e214ab1/download](https://app.zenhub.com/files/309315145/906718b8-0b2a-4ce1-ab39-b3265e214ab1/download)
```

**Comment by ala-ebi** [comment]
id is generated even if uploaded files contains errors (for example an inexistant trait), i think we should change that
