### ISSUE TITLE
Create API endpoint to download results of similarity analysis of reported traits

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#53]
Description:
As developer
I want an api endpoint
So that I can use to download analysed similarity result

Management Rules:
Rule 1: Endpoint - /v1/reported-traits/analysis/{analysisId}
Rule 2: HTTP Request Method - GET
Rule 3: Endpoint should accept an alphanumeric unique string representing the analysis id
Rule 4: Standard customized exception be thrown if analysis id is invalid
Rule 5: Endpoint should download analysis result

Acceptance Tests:
Given invalid analysisId
When user sends a get request to the endpoint
Properly described Exception should be returned in JSON format, detailing what is wrong

Given valid analysisId
The system should return a 3 column csv containing degree of similarity, user submitted trait, similar term found for each trait

**Comment by sajo-ebi** [comment]
API has been implemented in SandBox , the details are :

```
API : http://193.62.54.159/curation-traits/v1/reported-traits/fileupload/analysis/{{analysisId}}
Http Method : GET
```
