### ISSUE TITLE
Create a new Angular Based UI to support Edit template functionality

### ISSUE THREAD

**Issue by sajo-ebi** [EBISPOT/gwas-curation-service#6]

**Comment by ala-ebi** [comment]
@eks-ebi Could you please look at the app here http://193.62.54.159/gwas/curation/
We're looking for your feedback on:
1- Loggin in
2- Active submissions table (sorting is not fully functional as the Deposition sort is only on the UI side, we'll make it server side)
3- Details page after clicking on a submission (the history tab is static and contains dummy data)
4- Locking/unlocking (Edit tab & submission list), making sure a locked submission can't be edited by someone else
5- Uploading a new template, changes on the deposition side
6- Importing the new submission to curation
7- UX notes, suggestions and potentials improvements

**Comment by eks-ebi** [comment]
1) Logging in works perfectly for me
2) The layout of the Active submissions table is good and all fields are displayed as expected. Agree that the sorting is not working properly at the moment. Also the "Items per page" behaves strangely - selecting 5 or 10 items per page works, but if I select 20 items per page, it still only shows 10 items.
3) Details page looks good. I checked the Details for GCP ID, Details for PubMed ID, and Details for Submission ID - all OK. I like the idea of using icons for Studies, Associations and Samples, but the actual icons are not quite right for the GWAS context, e.g. for Samples it would be better to use a group of people - suggest discussion among the curators to pick best icons. Layout of the history tab looks great.
4) The locking/unlocking feature is good, but it's a bit confusing to understand when it is locked vs unlocked. Different text should be displayed next to the switch and in the tooltip when it is locked vs unlocked. Suggest changing the text to say "Locked for editing" when locked and "Unlocked for editing" when unlocked.
5) Uploading a new template - UX experience is good, except there is currently no way to reset/remove file if the template is invalid.
6) (still to do)
7) Overall experience is good, colour scheme, fonts etc. OK. I would maybe remove the indent from the headings on the Details page, e.g. "Details for PubMed ID..." is currently set in a few spaces from the edge and doesn't align with the text below. Other notes: Dashboard and Documentation links don't currently work so haven't tested. The GWAS Catalog logo should also be a link to the main site. Not sure what the Notification bell icon in the top right does - is this needed?

**Comment by sprintell** [comment]
Thanks for the detailed user report @eks-ebi , we'll combine this suggestions with the ongoing improvements that will be delivered by @ala-ebi  in the next iterations.

**Comment by eks-ebi** [comment]
I've now tested importing an edited submission to the curation interface and everything worked perfectly!

I imported, edited and re-imported this submission: http://193.62.54.159/gwas/curation/submissions/609feeeb47686b00016d335c
Import preview in curation interface here: http://snoopy:9580/gwas/curation/submissions/609feeeb47686b00016d335c?
Publication view here: http://snoopy:9580/gwas/curation/publication/31049583

I tested:
1. Removing a study that was previously there (study tag = Fetal meta) --> SUCCESS
2. Adding a new study (study tag = New study) --> SUCCESS
3. Editing various fields in an existing study (study tag = Maternal European) --> SUCCESS (see details below)
**note**: studies that were not edited/added/removed (study tags = Maternal Central Asian, Maternal meta) were correctly kept as they were after the original import

Specific edits to the existing study (study tag = Maternal European):
1. ADD controlled terms for fields Genotyping technology, Array manufacturer
2. CHANGE controlled terms/fixed values for Imputation, Ancestry category, Country of recruitment
3. ADD free text content for Array information, Statistical model, Study description, Cohort, Cohort specific reference, Sample description, Ancestry, Founder population
4. CHANGE Variant count: -1 (displayed as NA in curation int) > a number
5. CHANGE Reported trait: Preeclampsia (maternal genotype effect) [term not yet in database, so not imported] > Preeclampsia [term already in database, so imported successfully]
6. REMOVE efo_id from Mapped trait: EFO_0000668 | EFO_0005939 >  EFO_0000668
7. ADD efo_id to Mapped background trait
8. REMOVE row from Sample sheet
9. CHANGE value for Number of individuals, Number of cases, Number of controls
10. ADD new association row
11. ADD new note row

All changes were successfully imported and replaced the previous content for all fields

**Comment by eks-ebi** [comment]
Testing to ensure existing GCSTs are preserved when studies are edited and re-submitted:

1. Submitted template in deposition - 1 study, 1 sample row (discovery), 0 assocs:
[Submitted template](https://app.zenhub.com/files/309315145/aff6d690-9bc1-4716-a109-04817322f462/download)
[Submission page in deposition](http://193.62.54.159/gwas/deposition/submission/60c0c5b3d4917e0001c9d09d)

2. Imported into curation
[Import preview](http://snoopy:9580/gwas/curation/submissions/60c0c5b3d4917e0001c9d09d?)
**New study successfully imported as GCST90062720**

3. Edited template and resubmitted in new depo/curation app - same study, added a 2nd sample row (replication), added an EFO to mapped_trait column:
[Edited template](https://app.zenhub.com/files/309315145/5f002271-1e2d-433e-81c6-208cd7ca123d/download)
[Submission page in depo/curation](http://193.62.54.159/gwas/curation/submissions/60c0c5b3d4917e0001c9d09d)

4. Re-imported edited submission into curation
**Original study (Study Id: 80729642) not deleted, but marked Requires Review
New study created (Study Id: 80729654) with same GCST**

![Screenshot 2021-06-09 at 15.01.34.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/3ae09eee-dc6f-46c1-8304-0883ac15dca9)
![Screenshot 2021-06-09 at 15.01.55.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/f20e129b-3080-46d2-a456-6af525a810a5)

@ljwh2 Is this the expected behaviour? It would require a curator to delete the older study, which could be time-consuming and error-prone. And is it a problem that there are (at least temporarily) two studies in the database with the same GCST?

**Comment by earlEBI** [comment]
Tested various re-uploads, seems to work well. 
Suggestions for changes to the UI @ala-ebi @sajo-ebi : 

1. For the 'full dif' detailed report, only list those studies which have been added/removed. 
Currently, not very clear (eg. only one study has been removed, in the middle of the list):

![Screenshot 2021-06-11 at 09.45.43.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/3f592ebd-70f5-43fa-85c9-8f63e56a2586)

2. For the 'full dif' detailed report, for associations and samples, display 'old data => new data'. 
Currently, if sample is changed from 1431 to 11431, it shows confusingly as 'new data => old data':
![Screenshot 2021-06-11 at 10.13.55.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/4d7cfc32-5c73-49a6-a514-3f897a14571c)

#
Tested import and re-import. GCST stays the same as original submission, so no conflict with info given to user at original submission.

**Comment by eks-ebi** [comment]
Today tested trying to add summary statistics to an already-imported submission by:

1) importing submission without sumstats: 
Submission: http://193.62.54.159/gwas/deposition/submission/60e595a3b1d78f0001cfe4a2
Template: [https://app.zenhub.com/files/309315145/f48d45a2-7b26-4d59-b65d-b4ea1d2b88a7/download](https://app.zenhub.com/files/309315145/f48d45a2-7b26-4d59-b65d-b4ea1d2b88a7/download)
Import: http://snoopy.ebi.ac.uk:9580/gwas/curation/submissions/60e595a3b1d78f0001cfe4a2

2) transferring a new sumstats file to the Globus location:
Globus: https://app.globus.org/file-manager?origin_id=e3972722-df19-11eb-8325-45cc1b8ccd4a&origin_path=%2F

3) uploading a new template to the depo-curation app with the sumstats file name and md5:
Depo-curation: http://193.62.54.159/gwas/curation/submissions/60e595a3b1d78f0001cfe4a2
Updated template: [https://app.zenhub.com/files/309315145/cef64f9b-74eb-4bbb-88c7-c59e6184cc5f/download](https://app.zenhub.com/files/309315145/cef64f9b-74eb-4bbb-88c7-c59e6184cc5f/download)
Import: http://snoopy.ebi.ac.uk:9580/gwas/curation/submissions/60e595a3b1d78f0001cfe4a2

This did _not_ add the new summary statistics to the publication in the curation interface.
![Screenshot 2021-07-08 at 10.52.49.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/b0e2fae0-cd79-43a0-bd0e-9bb98c4d61a9)

**Comment by earlEBI** [comment]
Tested editing all types of metadata. 
1. Created submission in Deposition App (http://193.62.54.159/gwas/deposition/submission/60e80f36b1d78f0001128ab1)
2. Imported to the Curation App (http://snoopy.ebi.ac.uk:9680/gwas/curation/publication/32676622)
3. Edited template and reuploaded to DepoCuration app (http://193.62.54.159/gwas/curation/submissions/60e80f36b1d78f0001128ab1)
4. Re-imported to the Curation App

**Diff report works well. All changes were listed including:** 
- editing genotyping platform manufacturer
- imputation tick
- editing reported trait
- adding EFO
- editing Effect allele
- editing Effect allele frequency
- editing beta unit
- adding beta/OR range
- editing CoR
- editing/adding Note
- adding associations
- adding studies
- editing sample number

**Checked on Import:**
- GCSTs remain consistent 

**Issues:**
1. 
Metadata failed validation - didn't give report of why. Had to check on original submission page in Deposition App to see the errors. 
![Metadata failed validation - DepoCuration App - doesn't give details](https://user-images.githubusercontent.com/61545198/125061703-83c6c680-e0a5-11eb-978e-b1a30dcedbec.png)

2.
Originally imported studies remain visible in the Curation App publication page, listed as 'requires review'.
![Re-import - requires review](https://user-images.githubusercontent.com/61545198/125062759-a73e4100-e0a6-11eb-9872-702cfec07070.png)
Is this expected or should they be hidden? 

3. 
Originally, I submitted 1 association through the Deposition App, which is mapped both after original import: http://snoopy.ebi.ac.uk:9680/gwas/curation/studies/81162911/associations
and after re-import: http://snoopy.ebi.ac.uk:9680/gwas/curation/studies/81162959/associations
![Screenshot 2021-07-09 at 11 15 56](https://user-images.githubusercontent.com/61545198/125063177-11ef7c80-e0a7-11eb-82a5-ef1d5cfdd09d.png)
Other associations added through the DepoCuration App and then imported have not mapped:
Added to originally created study: http://snoopy.ebi.ac.uk:9680/gwas/curation/studies/81162993/associations
Newly added study: http://snoopy.ebi.ac.uk:9680/gwas/curation/studies/81163020/associations?associationId=81163024
![Screenshot 2021-07-09 at 11 17 53](https://user-images.githubusercontent.com/61545198/125063389-52e79100-e0a7-11eb-8f4e-18c6699eca8f.png)

4. 
Tested if I could add sumstats through DepoCuration App but the sumstats validating wheel just keeps spinning. As discussed in a meeting with Laura, this is not an absolutely necessary feature. Just to note attempted and failed.

5. 
Attempted to pick up on Elliot's submission above but there is no versioning history to be seen: http://193.62.54.159/gwas/curation/submissions/60e595a3b1d78f0001cfe4a2

**Comment by earlEBI** [comment]
Tested again as above but with different Curation App URL http://snoopy.ebi.ac.uk:9580/gwas/curation/publication/32865774

**All still applies except:** 
**Issue 2:** Not an issue. Duplicate/overwritten GCST entries are not shown. 
**Issue 3:** SNPs don't have mapping details but maybe that's expected at the moment. http://snoopy.ebi.ac.uk:9580/gwas/curation/studies/88200485/associations
![test1 study - no mapping info](https://user-images.githubusercontent.com/61545198/125110077-09fdff80-e0dc-11eb-8a95-a05e625d9708.png)

**Extension of issue 5 above:**
Even though the editing of metadata and import seems to work fine, 
http://193.62.54.159/gwas/curation/submissions/60e86eefb1d78f00011c9d41
![details are correct](https://user-images.githubusercontent.com/61545198/125110025-ffdc0100-e0db-11eb-87f5-6e9380b7d309.png)
the submission history tab remains empty:
![no submission history 2](https://user-images.githubusercontent.com/61545198/125110040-023e5b00-e0dc-11eb-868b-4dc05023748a.png)
