### ISSUE TITLE
Backend Feature to assign reported traits to studies in bulk

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#61]
**API endpoint to assign reported traits to studies resources in bulk via Multipart File upload**

**Description:**
As developer
I want an api endpoint
So that I can upload csv file for bulk assignment of reported traits to studies of a given submission

**Management Rules:**
Rule 1: Endpoint - /v1/submissions/{submissionId}/studies/files
Rule 2: HTTP Request Method - POST
Rule 3: Endpoint should accept validated Multipart file
Rule 4: Standard customized exception be thrown if operation fails
Rule 5: Endpoint should return list of updated studies

**Acceptance Tests:**
Given invalid csv file
When user sends a post request with the multipart file to the endpoint
Properly described Exception should be returned in JSON format, detailing what is wrong

**Given valid csv file uploaded**
If any of the trait name does not exist previously in the database such should be skipped and returned to the user as part of the report with description of why they were skipped
If no validation error occurs, the reported trait should be saved, createdBy, createDate, and uploadId should be stored
Full report of what happened to each trait must be returned to the user

**Comment by sajo-ebi** [comment]
Implemented the feature , finishing up the documentation n& unit testing

**Comment by sajo-ebi** [comment]
Deployed the Rest API for mapping traits with links

[Study Traits Mapping](http://hh-rke-wp-webadmin-09-worker-3.caas.ebi.ac.uk:31815/gwas/depo-curation/api/v1/studies/fileupload)

The Rest API documentation Url :

The Payload information can be found here

[Rest Docs](http://hh-rke-wp-webadmin-09-worker-3.caas.ebi.ac.uk:31815/gwas/depo-curation/api/docs/api-guide.html)

The file template can found in the following URL

[Template Study Traits file](http://hh-rke-wp-webadmin-09-worker-3.caas.ebi.ac.uk:31815/gwas/depo-curation/api/v1/reported-traits/fileupload/templates?file=study-trait)

**Comment by sajo-ebi** [comment]
@sprintell Please review.
