### ISSUE TITLE
BackEnd API to assign reported trait to a single study: 

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#62]
**_API endpoint to assign reported traits to a single study. This API should Update one study_**

**Description:**
As developer
I want an api endpoint
So that I can upload csv file for bulk assignment of reported traits to studies of a given submission

**Management Rules:**
Rule 0: Endpoint must be accessible to curator role only
Rule 1: Endpoint - /v1/studies/{studyId}
Rule 2: HTTP Request Method - PUT
Rule 3: Endpoint should accept study id
Rule 4: The Endpoint should accept validated StudyDto Object
Rule 5: Endpoint should return full attributes of the updated study

**Acceptance Tests:**
Given a wrong study id
When user sends a put request to the endpoint
Properly described Entity not found exception should be returned in JSON format

**Given invalid payload**
When user sends a put request to the endpoint
Properly described Exception should be returned in JSON format, detailing out what payload attribute is wrong

**Given a correct Study Id and valid payload**
**When** the front end sends a put request to the endpoint
The single study must be updated
Hateoas compliant updated study is  returned in JSON Format

**Comment by sajo-ebi** [comment]
Implemented the feature, finishing up documentation & unit testing

**Comment by sajo-ebi** [comment]
API deployed in Sandbox 

Method : PUT
[Update Study](http://hh-rke-wp-webadmin-09-worker-3.caas.ebi.ac.uk:31188/gwas/depo-curation/api/v1/studies/{studyId})

Payload information can be found in Rest Docs
[Rest Docs](http://hh-rke-wp-webadmin-09-worker-3.caas.ebi.ac.uk:31188/gwas/depo-curation/api/docs/api-guide.html)

Apart from these additional API's have been created for Studies Management
Method : GET
[Studies List ](http://hh-rke-wp-webadmin-09-worker-3.caas.ebi.ac.uk:31815/gwas/depo-curation/api/v1/studies)

[Retrieve Single Study](http://hh-rke-wp-webadmin-09-worker-3.caas.ebi.ac.uk:31188/gwas/depo-curation/api/v1/studies/{studyId})

[Retrieve Disease Traits based on study  ](http://hh-rke-wp-webadmin-09-worker-3.caas.ebi.ac.uk:31188/gwas/depo-curation/api/v1/studies/{studyId}/diseasetraits)

**Comment by sajo-ebi** [comment]
@sprintell Please review
