### ISSUE TITLE
Backend API endpoint to create one EFO trait resource

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#64]
API endpoint to create one EFO trait resource

**Description:**
As developer
I want an api endpoint
So that when I send a post request with the EFO trait payload one new EFO trait resource is created in the database

**Management Rules:**
Rule 0: Endpoint must be accessible to curator role only
Rule 1: Endpoint - /v1/efo-traits
Rule 2: HTTP Request Method - POST
Rule 3: Proper Assemblers, disassemblers and DTO with validation rules
Rule 4: The Endpoint should accept validated EFOTrait DTO Object
Rule 5: Standard customized exception be thrown if operation fails

**Acceptance Tests:**
**_Given_** a JSON payload containing EFO trait data
When the front end sends a post request with the payload to the endpoint
If EFO trait name existed previously in the database, Exception with corresponding response status must be returned to the user
If no validation error occurs, the EFO trait should be saved , createdBy, and createDate must be saved also
The generated EFO trait id, with correct response status must be returned to the user

**Comment by ala-ebi** [comment]
Request:
POST /efo-traits/{traitId}

{
"trait": "",
"shortForm":"",
"uri": ""
}
Response:
HTTP201

{
"efoTraitId" :"",
"trait": "",
"shortForm":"",
"uri": ""
"created": {}
"updated": {}
}
