### ISSUE TITLE
Backend API endpoint to get All EFO trait resources

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#65]
API endpoint to get All reported trait resources

**Description:**
As developer
I want an api endpoint
So that I can get paginated list of all EFO traits in the database in JSON Format

**Management Rules:**
Rule 0: Endpoint must be accessible to curator role only
Rule 1: Endpoint - /v1/efo-traits
Rule 2: HTTP Request Method - GET
Rule 3: Endpoint should accept filter, and sort parameters as in /v1/efo-traits?trait=...&page=0&size=20 &sort=name,desc
Rule 4: HATEOAS, sorting, pagination, and some search and filter specification

**Acceptance Tests:**
Given no parameter
When the front end sends a get request to the endpoint
Hateoas compliant list of reported traits is  returned in JSON Format

**_Given_** sorting, pagination, and/or some search and filter parameters
When the front end sends a get request to the endpoint
Hateoas compliant filtered list of EFO traits satisfying the conditions in the url parameter must be returned

**Comment by ala-ebi** [comment]
Request:
POST /efo-traits/{traitId}

{
   "trait": "",
   "shortForm":"",
   "uri": ""
}
Response:
HTTP201

{
   "efoTraitId" :"",
   "trait": "",
   "shortForm":"",
   "uri": ""
   "created": {}
   "updated": {}
}
