### ISSUE TITLE
Backend API endpoint to get one EFO trait resource

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#66]
API endpoint to get one EFO trait resource

**Description:**
As developer
I want an api endpoint
So that I can get full details of a single EFO trait in JSON Format

**Management Rules:**
Rule 0: Endpoint must be accessible to curator role only
Rule 1: Endpoint - /v1/efo-traits/{efoTraitId}
Rule 2: HTTP Request Method - GET
Rule 3: Endpoint should accept EFO trait id
Rule 4: Endpoint should return full attributes of the EFO trait including creator, modifier and time info

**Acceptance Tests:**
Given a correct EFO trait Id
When the front end sends a get request to the endpoint
A single corresponding EFO traits is returned in JSON Format

**_Given_** a wrong efo id
When the front end sends a get request to the endpoint
Properly described Resource not found exception should be returned as JSON payload

**Comment by ala-ebi** [comment]
Request:
GET /efo-traits/{traitId}
Response:
HTTP200

```
{
   "efoTraitId" :"",
   "trait": "",
   "shortForm":"",
   "uri": ""
   "created": {}
   "updated": {}
}
```
