### ISSUE TITLE
Avoid calling sumstats service when depo curation is used

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-curation-service#67]
Currently, when curators use the depo curation app, it calls the deposition app, which in turn calls the sumstats service, which in turn revalidates the sumstats and restages them for release. Presently, changes to sumstats like this are unsupported and it uses  a lot resources to perform such tasks. We should therefore prevent the sumstats service from being called when depo curation is used

**Comment by jdhayhurst** [comment]
Additionally, (I can create another ticket if necessary) the original submitter is emailed every time the submission is redone by the curator. Is this the expected behaviour?

**Comment by buniello** [comment]
@ljwh2 @jdhayhurst: I believe this ticket should be prioritised when possible, as sumstats get validated every time the curators modify the submission form in the depo curation app -- and authors keep getting validation emails every time this happens. I think the multiple emails annoy the submitters (see Marta Guindo Martinez and Eric Harshfiled's emails). 
Also, calling the sumstats service every time delays curation pipeline--importing times.

**Comment by sajo-ebi** [comment]
Code changes has been deployed in Sandbox , there was an issue with submission in Sandbox where the submission  were stuck in validating stage, have resolved the issue now , need to test the changes in Sandbox

**Comment by sajo-ebi** [comment]
Changes have been tested in Sandbox with @jdhayhurst they look good , need deployment in production

**Comment by sajo-ebi** [comment]
Code has been deployed in production

**Comment by eks-ebi** [comment]
@sajo-ebi @ljwh2  We discussed that these changes should prevent submitters from being sent a validation email when changes are made to their submission by a curator in depo-curation, and I was asked to test. Unfortunately, this issue does **not** seem to be fixed:

* I opened an old submission that I created in deposition (i.e. I am the submitter) - https://www.ebi.ac.uk/gwas/depo-curation/submissions/620a8eb02101880001d12255
* I made a trivial change to the template (added a new note in the notes tab) and uploaded the edited template in depo-curation.
* I **did** receive a validation email after making these changes:

> Dear Elliot Sollis,
> 
> The summary statistics for 34424336 - Different Pigmentation Risk Loci for High-Risk Monosomy 3 and Low-Risk Disomy 3 Uveal Melanomas. by Mobuchon L et al., were successfully validated and submitted to the GWAS Catalog.
> 
> Following submission the accession ID(s) for your submission will be available to download by pressing on the 'Download Study Accessions' button on the studies page.
> 
> Thanks for sharing your data with us.
> 
> Best wishes,
> GWAS Catalog team

**Comment by ljwh2** [comment]
@eks-ebi please create a new ticket for the email issue

**Comment by eks-ebi** [comment]
new ticket for the email issue here: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/627
