### ISSUE TITLE
Backend API endpoint to fully Update single EFO trait resource

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#69]
API endpoint to fully Update single EFO trait resource

**Description:**
As developer
I want an api endpoint
So that I can change / update all the attributes of a single EFO trait

**Management Rules:**
Rule 0: Endpoint must be accessible to curator role only
Rule 1: Endpoint - /v1/efo-traits/{efoTraitId}
Rule 2: HTTP Request Method - PUT
Rule 3: Endpoint should accept EFO trait id
Rule 4: The Endpoint should accept validated EFO rait DTO Object
Rule 5: Endpoint should return full attributes of the updated EFO trait

**Acceptance Tests:**
Given a wrong EFO trait id
When user sends a put request to the endpoint
Properly described Entity not found exception should be returned in JSON format

**Given invalid payload**
When user sends a put request to the endpoint
Properly described Exception should be returned in JSON format, detailing out what payload attribute is wrong

**Given a correct reported Id and valid payload**
When the front end sends a put request to the endpoint
The single reported trait must be updated
Hateoas compliant list of the updated EFO trait is  returned in JSON Format

**Comment by ala-ebi** [comment]
Request:
PUT /efo-traits/{traitId}
```
{
   "trait": "",
   "shortForm":"",
   "uri": ""
}
```
Response:
HTTP200
```
{
   "efoTraitId" :"",
   "trait": "",
   "shortForm":"",
   "uri": ""
   "created": {}
   "updated": {}
}
```
