### ISSUE TITLE
Backend API endpoint to create new efo Trait resource via Multipart File upload

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-curation-service#73]
**API endpoint to create new efo Trait resource via Multipart File upload**

**Description:**
As developer
I want an api endpoint
So that I can upload csv file for bulk creation of efo traits

**Management Rules:**
Rule 1: Endpoint - /v1/efo-traits/files
Rule 2: HTTP Request Method - POST
Rule 3: Endpoint should accept validated Multipart file
Rule 4: Standard customized exception be thrown if operation fails
Rule 5: Endpoint should return list of created efo traits with their auto generated ids
Rule 6:  There should be an endpoint /v1/templates?file=efo-traits  
to retrieve the template csv with pre filled sample contents

**Acceptance Tests:**
Given invalid csv file  
When user sends a post request with the multipart file to the endpoint
Properly described Exception should be returned in JSON format, detailing what is wrong

**Given valid csv file uploaded**
If any of the efo trait name existed previously in the database such should be skipped and returned to the user as part of the report with description of why they were skipped
If no validation error occurs, the efo trait should be saved, createdBy, createDate, and uploadId should be stored
Full report of what happened to each efo trait must be returned to the user

**Comment by ala-ebi** [comment]
Request:
POST /efo-traits/bulk-upload
Form-Data: `key: multipartFile, value: the file`
Response:
HTTP201

```
{
   "trait": "",
   "accession" : "",
   "uploadComment": ""
}
```
